name: Cam4 to Telegram 2GB
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Nom du modèle'
        required: true
        default: 'anjelo79'
      duration:
        description: 'Durée en secondes'
        required: true
        default: '7200'

jobs:
  run_recorder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Tools
        run: |
          pip install telethon yt-dlp
          sudo apt update && sudo apt install -y ffmpeg

      - name: Record and Upload
        run: |
          # On lance le script d'upload en arrière-plan
          python upload.py & 
          
          # On lance l'enregistrement avec segmentation
          yt-dlp "https://www.cam4.com/${{ github.event.inputs.username }}" \
          --downloader ffmpeg \
          --downloader-args "ffmpeg:-t ${{ github.event.inputs.duration }} -fs 1900M" \
          -o "%(uploader)s_%(os_str)s_%(date)s_%(time)s.%(ext)s"

      - name: Upload to Telegram
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python upload.py
